enum REWARD_OPTION {
	TOWER,
	ARC_TOWER,
	TOWER_ACCURACY,
	FIRE_RATE_MINOR,
	FIRE_RATE_MAJOR,
	DAMAGE_MINOR,
	DAMAGE_MAJOR,
	SHIELD_RECHARGE_MINOR,
	SHIELD_RECHARGE_MAJOR,
	SHIELD_STRENGTH_MINOR,
	SHIELD_STRENGTH_MAJOR,
	SHIELD_REPULSION_MINOR,
	SHIELD_REPULSION_MAJOR
}